version: '3'

services:
  mariadb-group-1-origin:
    image: mariadb:latest
    container_name: mariadb-group-1-origin
    environment:
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=1234!!
      - MARIADB_ROOT_PASSWORD=1234!!
    ports:
      - "3306:3306"
    volumes:
      - "./infra/group-1/origin/scripts/:/docker-entrypoint-initdb.d/"
      - "./infra/group-1/origin/config/my.cnf:/etc/mysql/my.cnf"
      - "./infra/group-1/origin/data/:/var/lib/mysql/"
      - "./infra/group-1/origin/log/:/var/log/mysql/"

  mariadb-group-1-replica:
    image: mariadb:latest
    container_name: mariadb-group-1-replica
    environment:
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=1234!!
      - MARIADB_ROOT_PASSWORD=1234!!
    ports:
      - "3307:3306"
    volumes:
      - "./infra/group-1/replica/scripts/:/docker-entrypoint-initdb.d/"
      - "./infra/group-1/replica/config/:/etc/mysql/my.cnf"
      - "./infra/group-1/replica/data/:/var/lib/mysql/"
      - "./infra/group-1/replica/log/:/var/log/mysql/"

  mariadb-group-2-origin:
    image: mariadb:latest
    container_name: mariadb-group-2-origin
    environment:
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=1234!!
      - MARIADB_ROOT_PASSWORD=1234!!
    ports:
      - "3316:3306"
    volumes:
      - "./infra/group-2/origin/scripts/:/docker-entrypoint-initdb.d/"
      - "./infra/group-2/origin/config/my.cnf:/etc/mysql/my.cnf"
      - "./infra/group-2/origin/data/:/var/lib/mysql/"
      - "./infra/group-2/origin/log/:/var/log/mysql/"

  mariadb-group-2-replica:
    image: mariadb:latest
    container_name: mariadb-group-2-replica
    environment:
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=1234!!
      - MARIADB_ROOT_PASSWORD=1234!!
    ports:
      - "3317:3306"
    volumes:
      - "./infra/group-2/replica/scripts/:/docker-entrypoint-initdb.d/"
      - "./infra/group-2/replica/config/my.cnf:/etc/mysql/my.cnf"
      - "./infra/group-2/replica/data/:/var/lib/mysql/"
      - "./infra/group-2/replica/log/:/var/log/mysql/"

  redis:
    image: redis:latest
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_NODENAME:rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

