spring:
  redis:
    host: localhost
    port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    root: info
    org:
      jooq: debug
    com:
      zaxxer:
        hikari: debug

shard-group:
  strategy: RANGE
  nodes:
    -
      group-id: 1
      read-only: false
      url: jdbc:mariadb://localhost:3306/point
      username: root
      password: 1234!!
      driver-class-name: org.mariadb.jdbc.Driver
      minKey: 1
      maxKey: 300000
    -
      group-id: 1
      read-only: true
      url: jdbc:mariadb://localhost:3307/point
      username: root
      password: 1234!!
      driver-class-name: org.mariadb.jdbc.Driver
      minKey: 1
      maxKey: 300000
    -
      group-id: 2
      read-only: false
      url: jdbc:mariadb://localhost:3316/point
      username: root
      password: 1234!!
      driver-class-name: org.mariadb.jdbc.Driver
      minKey: 300001
      maxKey: 9223372036854775807
    -
      group-id: 2
      read-only: true
      url: jdbc:mariadb://localhost:3317/point
      username: root
      password: 1234!!
      driver-class-name: org.mariadb.jdbc.Driver
      minKey: 300001
      maxKey: 9223372036854775807
